import { Plus, Trash2, X, AlertTriangle, CheckCircle2 } from "lucide-react";
import { useCallback, useState } from "react";
import {
  BarChart,
  Bar,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
  ReferenceLine,
} from "recharts";
import {
  ManualStint,
  RaceConfiguration,
  Stint,
  TimelineData,
  TyreWearData,
} from "@/app/types/TyTypes";
import { TyrePreferences } from "./TyreSettings";
import { getEffectiveTyreData } from "../TyreMath";

export const DEFAULT_RACECONFIGURATION: RaceConfiguration = {
  RaceLaps: 0,
};

const TYRE_COLORS: Record<string, string> = {
  soft: "#dc2626",
  medium: "#eab308",
  hard: "#ffffff",
  wet: "#1d4ed8",
};

const TYRE_LABELS: Record<string, string> = {
  soft: "S",
  medium: "M",
  hard: "H",
  wet: "W",
};

interface RaceSettingsProps {
  currentConfig?: RaceConfiguration;
  currentManualStints: ManualStint[];
  tyreData: Record<string, TyreWearData>;
  tyrePreferences: TyrePreferences;
  onClose: () => void;
  onSave: (config: RaceConfiguration, manualStints: ManualStint[]) => void;
  autoTimelineData: TimelineData[];
  autoTimelineStints: Stint[];
  isAutoGenerated: boolean;
}

export default function RaceSettings({
  currentConfig = DEFAULT_RACECONFIGURATION,
  currentManualStints,
  tyreData,
  tyrePreferences,
  onClose,
  onSave,
}: RaceSettingsProps) {
  const [config, setConfig] = useState<RaceConfiguration>(currentConfig);
  const [manualStints, setManualStints] =
    useState<ManualStint[]>(currentManualStints);
  const [selectedStintId, setSelectedStintId] = useState<string | null>(
    manualStints.length > 0 ? manualStints[0].id : null,
  );

  // -- Helpers --
  const getTotalLapsPlanned = useCallback(
    () => manualStints.reduce((acc, s) => acc + s.laps, 0),
    [manualStints],
  );

  const handleAddStint = () => {
    const newStint: ManualStint = {
      id: Math.random().toString(36).substr(2, 9),
      tyre: "soft",
      laps: Math.max(1, config.RaceLaps - getTotalLapsPlanned()),
    };
    const newStints = [...manualStints, newStint];
    setManualStints(newStints);
    setSelectedStintId(newStint.id);
  };

  const handleRemoveStint = (id: string) => {
    const newStints = manualStints.filter((s) => s.id !== id);
    setManualStints(newStints);
    if (selectedStintId === id) {
      setSelectedStintId(newStints.length > 0 ? newStints[0].id : null);
    }
  };

  const handleUpdateStint = (
    id: string,
    field: keyof ManualStint,
    value: string | number,
  ) => {
    setManualStints((prev) =>
      prev.map((s) => (s.id === id ? { ...s, [field]: value } : s)),
    );
  };

  const handleSave = () => {
    onSave(config, manualStints);
    onClose();
  };

  const previewData = [
    {
      name: "Strategy",
      ...manualStints.reduce(
        (acc, stint, index) => {
          acc[`stint_${index}_${stint.tyre}`] = stint.laps;
          return acc;
        },
        {} as Record<string, number>,
      ),
    },
  ];

  const selectedStint = manualStints.find((s) => s.id === selectedStintId);

  const effectiveData = selectedStint
    ? getEffectiveTyreData(selectedStint.tyre, tyreData, tyrePreferences)
    : null;

  const selectedTyreWear = effectiveData ? effectiveData.wearPerLap : 0;

  const estWear = selectedStint ? selectedTyreWear * selectedStint.laps : 0;

  const maxSafeLaps =
    selectedTyreWear > 0
      ? Math.floor(
          (100 - tyrePreferences.preferredSwitchoverPoint) / selectedTyreWear,
        )
      : 0;

  const isOverLimit =
    estWear > 100 - (tyrePreferences.preferredSwitchoverPoint || 0);

  const maxStintsReached = getTotalLapsPlanned() >= config.RaceLaps;

  return (
    <div className="fixed inset-0 bg-neutral-950/95 flex flex-col items-center justify-center p-4 z-50 overflow-y-auto">
      <div className="w-full max-w-4xl bg-zinc-100 dark:bg-neutral-900 rounded-xl flex flex-col border border-neutral-800 shadow-2xl overflow-hidden max-h-[90vh]">
        {/* Header */}
        <div className="flex justify-between items-center p-6 border-b border-neutral-800 bg-zinc-100 dark:bg-neutral-900 sticky top-0 z-10">
          <h2 className="text-xl font-bold  flex items-center gap-2">
            Race & Strategy Editor
          </h2>
          <button onClick={onClose} className=" cursor-pointer">
            <X />
          </button>
        </div>

        <div className="flex flex-col md:flex-row h-full overflow-hidden">
          <div className="w-full md:w-1/3 border-r border-neutral-800 overflow-y-auto p-4 flex flex-col gap-3">
            <div className="flex justify-between items-center mb-2">
              <span className="text-sm font-semibold ">
                Stints
              </span>
              <span
                className={`text-xs ${
                  getTotalLapsPlanned() === config.RaceLaps
                    ? "text-green-500"
                    : "text-red-500"
                }`}
              >
                {getTotalLapsPlanned()} / {config.RaceLaps} Laps
              </span>
            </div>

            {manualStints.map((stint, index) => (
              <div
                key={stint.id}
                onClick={() => setSelectedStintId(stint.id)}
                className={`p-3 rounded-lg border cursor-pointer flex items-center justify-between ${
                  selectedStintId === stint.id
                    ? "bg-zinc-200 dark:bg-neutral-800 border-neutral-600 ring-1 ring-neutral-500"
                    : "bg-zinc-200/50 dark:bg-neutral-800/50 border-neutral-800 hover:bg-zinc-200 dark:hover:bg-neutral-800"
                }`}
              >
                <div className="flex items-center gap-3">
                  <div
                    className="w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm border-2 shadow-sm"
                    style={{
                      borderColor: TYRE_COLORS[stint.tyre],
                      color: TYRE_COLORS[stint.tyre],
                    }}
                  >
                    {TYRE_LABELS[stint.tyre]}
                  </div>
                  <div className="flex flex-col">
                    <span className=" text-sm font-medium">
                      Stint {index + 1}
                    </span>
                    <span className=" text-xs">
                      {stint.laps} Laps
                    </span>
                  </div>
                </div>
                {manualStints.length > 1 && (
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleRemoveStint(stint.id);
                    }}
                    className=" hover:text-red-500 p-1"
                  >
                    <Trash2 className="h-4 w-4 cursor-pointer" />
                  </button>
                )}
              </div>
            ))}

            <button
              onClick={handleAddStint}
              className={`w-full ${
                maxStintsReached
                  ? "opacity-50 cursor-not-allowed"
                  : "cursor-pointer"
              } py-3 border-2 border-dashed border-neutral-700  rounded-lg flex items-center justify-center gap-2 text-sm font-semibold`}
              disabled={maxStintsReached}
            >
              <Plus className="h-4 w-4" /> Add Stint
            </button>
          </div>

          {/* RIGHT COLUMN: Editor & Visualization */}
          <div className="w-full md:w-2/3 p-6 flex flex-col gap-6 overflow-y-hide">
            {/* 1. Global Race Settings */}
            <div className="grid grid-cols-2 gap-4 pb-4 border-b border-neutral-800">
              <div className="flex flex-col gap-1">
                <label className="text-xs  uppercase font-bold tracking-wider">
                  Total Race Laps
                </label>
                <input
                  type="number"
                  value={config.RaceLaps}
                  onChange={(e) =>
                    setConfig({
                      ...config,
                      RaceLaps: parseInt(e.target.value) || 0,
                    })
                  }
                  className="bg-zinc-100 dark:bg-neutral-950 border border-neutral-700 rounded p-2 focus:outline-none focus:border-neutral-500"
                />
              </div>
              <div className="flex flex-col justify-end">
                <div className="flex items-center gap-2 text-sm bg-zinc-100 dark:bg-neutral-950 p-2 rounded border border-neutral-800">
                  {Math.abs(config.RaceLaps - getTotalLapsPlanned()) === 0 ? (
                    <CheckCircle2 className="text-green-500 h-5 w-5" />
                  ) : (
                    <AlertTriangle className="text-yellow-500 h-5 w-5" />
                  )}
                  <span>
                    {getTotalLapsPlanned() > config.RaceLaps
                      ? `${
                          getTotalLapsPlanned() - config.RaceLaps
                        } laps too many`
                      : getTotalLapsPlanned() < config.RaceLaps
                        ? `${
                            config.RaceLaps - getTotalLapsPlanned()
                          } laps remaining`
                        : "Strategy length matches Race length"}
                  </span>
                </div>
              </div>
            </div>

            {/* 2. Visual Timeline Preview */}
            <div className="h-32 w-full bg-zinc-100 dark:bg-neutral-950 rounded-lg p-2 border border-neutral-800 relative">
              <span className="absolute top-2 left-2 text-xs  z-10">
                Projected Timeline
              </span>
              <ResponsiveContainer width="100%" height="100%">
                <BarChart
                  layout="vertical"
                  data={previewData}
                  margin={{ top: 15, right: 0, left: 0, bottom: 0 }}
                >
                  <XAxis type="number" domain={[0, config.RaceLaps]} hide />
                  <YAxis type="category" dataKey="name" hide />
                  <Tooltip
                    cursor={{ fill: "transparent" }}
                    contentStyle={{
                      backgroundColor: "#171717",
                      border: "1px solid #404040",
                      color: "#fff",
                    }}
                  />
                  {manualStints.map((stint, index) => (
                    <Bar
                      key={`stint_${index}_${stint.tyre}`}
                      dataKey={`stint_${index}_${stint.tyre}`}
                      stackId="a"
                      fill={TYRE_COLORS[stint.tyre]}
                      isAnimationActive={false}
                    />
                  ))}
                  <ReferenceLine x={config.RaceLaps} stroke="#404040" />
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* 3. Selected Stint Editor */}
            {selectedStint ? (
              <div className="bg-zinc-100/50 dark:bg-neutral-800/50 rounded-xl p-4 border border-neutral-700 flex flex-col gap-4">
                <div className="flex justify-between items-center">
                  <h3 className="text-lg font-bold">
                    Edit Stint Details
                  </h3>
                  <div className="flex gap-2 bg-zinc-300 p-2 rounded-lg dark:bg-transparent dark:p-0 dark:rounded-none">
                    {["soft", "medium", "hard", "wet"].map((t) => (
                      <button
                        key={t}
                        onClick={() =>
                          handleUpdateStint(selectedStint.id, "tyre", t)
                        }
                        className={`w-8 h-8 rounded-full border-2 cursor-pointer ${
                          selectedStint.tyre === t
                            ? "scale-110 ring-2 ring-white"
                            : "opacity-40 hover:opacity-100"
                        }`}
                        style={{
                          backgroundColor: "transparent",
                          borderColor: TYRE_COLORS[t],
                          color: TYRE_COLORS[t],
                        }}
                      >
                        {TYRE_LABELS[t]}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-6">
                  <div className="flex flex-col gap-2">
                    <label className="text-sm ">
                      Laps in Stint
                    </label>
                    <div className="flex items-center gap-2">
                      <input
                        type="range"
                        min={1}
                        /* max = race laps - other stints' laps */
                        max={
                          config.RaceLaps -
                          manualStints
                            .filter((s) => s.id !== selectedStint.id)
                            .reduce((acc, s) => acc + s.laps, 0)
                        }
                        value={selectedStint.laps}
                        onChange={(e) =>
                          handleUpdateStint(
                            selectedStint.id,
                            "laps",
                            parseInt(e.target.value),
                          )
                        }
                        className="grow accent-neutral-300"
                      />
                      <input
                        type="number"
                        min={1}
                        value={selectedStint.laps}
                        onChange={(e) =>
                          handleUpdateStint(
                            selectedStint.id,
                            "laps",
                            parseInt(e.target.value),
                          )
                        }
                        className="w-16 bg-zinc-100 dark:bg-neutral-950 border border-neutral-700 rounded p-1 text-center "
                      />
                    </div>
                  </div>

                  {/* STATS BOX */}
                  <div className="bg-zinc-100 dark:bg-neutral-900 rounded-lg p-3 border border-neutral-800 text-xs flex flex-col gap-1">
                    <span className="font-bold  mb-1">
                      Projections
                    </span>
                    <div className="flex justify-between">
                      <span className="">Wear/Lap:</span>
                      <span className="">
                        {selectedTyreWear > 0
                          ? `${selectedTyreWear.toFixed(2)}%`
                          : "No Data"}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="">Rec. Max Laps:</span>
                      <span className="">{maxSafeLaps}</span>
                    </div>
                    <div className="flex justify-between border-t border-neutral-800 pt-1 mt-1">
                      <span className="">
                        Est. Life Remaining:
                      </span>
                      <span
                        className={`font-bold ${
                          isOverLimit ? "text-red-500" : "text-green-500"
                        }`}
                      >
                        {selectedStint ? (100 - estWear).toFixed(1) : "N/A"}%
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="h-full flex items-center justify-center  italic">
                Select a stint to edit details
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 bg-zinc-100 dark:bg-neutral-900 border-t border-neutral-800 flex justify-end gap-2">
          <button
            onClick={onClose}
            className="px-6 py-2 rounded-lg hover:bg-zinc-200 dark:hover:bg-neutral-800 cursor-pointer"
          >
            Cancel
          </button>
          <button
            onClick={handleSave}
            className="px-6 py-2 rounded-lg bg-zinc-200 dark:bg-white text-black font-bold hover:bg-zinc-300 dark:hover:bg-neutral-200 shadow-lg shadow-white/10 cursor-pointer"
          >
            Save Configuration
          </button>
        </div>
      </div>
    </div>
  );
}
