import { Plus, Trash2, X, AlertTriangle, CheckCircle2 } from "lucide-react";
import { useCallback, useState } from "react";
import {
  BarChart,
  Bar,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
  ReferenceLine,
} from "recharts";
import {
  ManualStint,
  RaceConfiguration,
  Stint,
  TimelineData,
  TyreWearData,
} from "@/app/types/TyTypes";
import { TyrePreferences } from "@/app/types/TyTypes";
import { getEffectiveTyreData } from "../TyreMath";

export const DEFAULT_RACECONFIGURATION: RaceConfiguration = {
  RaceLaps: 0,
};

const TYRE_COLORS: Record<string, string> = {
  soft: "#dc2626",
  medium: "#eab308",
  hard: "#ffffff",
  wet: "#1d4ed8",
};

const TYRE_LABELS: Record<string, string> = {
  soft: "S",
  medium: "M",
  hard: "H",
  wet: "W",
};

interface RaceSettingsProps {
  currentConfig?: RaceConfiguration;
  currentManualStints: ManualStint[];
  tyreData: Record<string, TyreWearData>;
  tyrePreferences: TyrePreferences;
  onClose: () => void;
  onSave: (config: RaceConfiguration, manualStints: ManualStint[]) => void;
  autoTimelineData: TimelineData[];
  autoTimelineStints: Stint[];
  isAutoGenerated: boolean;
}

export default function RaceSettings({
  currentConfig = DEFAULT_RACECONFIGURATION,
  currentManualStints,
  tyreData,
  tyrePreferences,
  onClose,
  onSave,
}: RaceSettingsProps) {
  const [config, setConfig] = useState<RaceConfiguration>(currentConfig);
  const [manualStints, setManualStints] =
    useState<ManualStint[]>(currentManualStints);
  const [selectedStintId, setSelectedStintId] = useState<string | null>(
    manualStints.length > 0 ? manualStints[0].id : null,
  );

  // -- Helpers --
  const getTotalLapsPlanned = useCallback(
    () => manualStints.reduce((acc, s) => acc + s.laps, 0),
    [manualStints],
  );

  const handleAddStint = () => {
    const newStint: ManualStint = {
      id: Math.random().toString(36).substr(2, 9),
      tyre: "soft",
      laps: Math.max(1, config.RaceLaps - getTotalLapsPlanned()),
    };
    const newStints = [...manualStints, newStint];
    setManualStints(newStints);
    setSelectedStintId(newStint.id);
  };

  const handleRemoveStint = (id: string) => {
    const newStints = manualStints.filter((s) => s.id !== id);
    setManualStints(newStints);
    if (selectedStintId === id) {
      setSelectedStintId(newStints.length > 0 ? newStints[0].id : null);
    }
  };

  const handleUpdateStint = (
    id: string,
    field: keyof ManualStint,
    value: string | number,
  ) => {
    setManualStints((prev) =>
      prev.map((s) => (s.id === id ? { ...s, [field]: value } : s)),
    );
  };

  const handleSave = () => {
    onSave(config, manualStints);
    onClose();
  };

  const previewData = [
    {
      name: "Strategy",
      ...manualStints.reduce(
        (acc, stint, index) => {
          acc[`stint_${index}_${stint.tyre}`] = stint.laps;
          return acc;
        },
        {} as Record<string, number>,
      ),
    },
  ];

  const selectedStint = manualStints.find((s) => s.id === selectedStintId);

  const effectiveData = selectedStint
    ? getEffectiveTyreData(selectedStint.tyre, tyreData, tyrePreferences)
    : null;

  const selectedTyreWear = effectiveData ? effectiveData.wearPerLap : 0;

  const estWear = selectedStint ? selectedTyreWear * selectedStint.laps : 0;

  const maxSafeLaps =
    selectedTyreWear > 0
      ? Math.floor(
          (100 - tyrePreferences.preferredSwitchoverPoint) / selectedTyreWear,
        )
      : 0;

  const isOverLimit =
    estWear > 100 - (tyrePreferences.preferredSwitchoverPoint || 0);

  const maxStintsReached = getTotalLapsPlanned() >= config.RaceLaps;

  return (
    <div className="fixed inset-0 z-50 flex flex-col items-center justify-center overflow-y-auto bg-neutral-950/95 p-4">
      <div className="flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-xl border border-neutral-800 bg-zinc-100 shadow-2xl dark:bg-neutral-900">
        {/* Header */}
        <div className="sticky top-0 z-10 flex items-center justify-between border-b border-neutral-800 bg-zinc-100 p-6 dark:bg-neutral-900">
          <h2 className="flex items-center gap-2 text-xl font-bold">
            Race & Strategy Editor
          </h2>
          <button onClick={onClose} className="cursor-pointer">
            <X />
          </button>
        </div>

        <div className="flex h-full flex-col overflow-hidden md:flex-row">
          <div className="flex w-full flex-col gap-3 overflow-y-auto border-r border-neutral-800 p-4 md:w-1/3">
            <div className="mb-2 flex items-center justify-between">
              <span className="text-sm font-semibold">Stints</span>
              <span
                className={`text-xs ${
                  getTotalLapsPlanned() === config.RaceLaps
                    ? "text-green-500"
                    : "text-red-500"
                }`}
              >
                {getTotalLapsPlanned()} / {config.RaceLaps} Laps
              </span>
            </div>

            {manualStints.map((stint, index) => (
              <div
                key={stint.id}
                onClick={() => setSelectedStintId(stint.id)}
                className={`flex cursor-pointer items-center justify-between rounded-lg border p-3 ${
                  selectedStintId === stint.id
                    ? "border-neutral-600 bg-zinc-200 ring-1 ring-neutral-500 dark:bg-neutral-800"
                    : "border-neutral-800 bg-zinc-200/50 hover:bg-zinc-200 dark:bg-neutral-800/50 dark:hover:bg-neutral-800"
                }`}
              >
                <div className="flex items-center gap-3">
                  <div
                    className="flex h-8 w-8 items-center justify-center rounded-full border-2 text-sm font-bold shadow-sm"
                    style={{
                      borderColor: TYRE_COLORS[stint.tyre],
                      color: TYRE_COLORS[stint.tyre],
                    }}
                  >
                    {TYRE_LABELS[stint.tyre]}
                  </div>
                  <div className="flex flex-col">
                    <span className="text-sm font-medium">
                      Stint {index + 1}
                    </span>
                    <span className="text-xs">{stint.laps} Laps</span>
                  </div>
                </div>
                {manualStints.length > 1 && (
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleRemoveStint(stint.id);
                    }}
                    className="p-1 hover:text-red-500"
                  >
                    <Trash2 className="h-4 w-4 cursor-pointer" />
                  </button>
                )}
              </div>
            ))}

            <button
              onClick={handleAddStint}
              className={`w-full ${
                maxStintsReached
                  ? "cursor-not-allowed opacity-50"
                  : "cursor-pointer"
              } flex items-center justify-center gap-2 rounded-lg border-2 border-dashed border-neutral-700 py-3 text-sm font-semibold`}
              disabled={maxStintsReached}
            >
              <Plus className="h-4 w-4" /> Add Stint
            </button>
          </div>

          {/* RIGHT COLUMN: Editor & Visualization */}
          <div className="overflow-y-hide flex w-full flex-col gap-6 p-6 md:w-2/3">
            {/* 1. Global Race Settings */}
            <div className="grid grid-cols-2 gap-4 border-b border-neutral-800 pb-4">
              <div className="flex flex-col gap-1">
                <label className="text-xs font-bold tracking-wider uppercase">
                  Total Race Laps
                </label>
                <input
                  type="number"
                  value={config.RaceLaps}
                  onChange={(e) =>
                    setConfig({
                      ...config,
                      RaceLaps: parseInt(e.target.value) || 0,
                    })
                  }
                  className="rounded border border-neutral-700 bg-zinc-100 p-2 focus:border-neutral-500 focus:outline-none dark:bg-neutral-950"
                />
              </div>
              <div className="flex flex-col justify-end">
                <div className="flex items-center gap-2 rounded border border-neutral-800 bg-zinc-100 p-2 text-sm dark:bg-neutral-950">
                  {Math.abs(config.RaceLaps - getTotalLapsPlanned()) === 0 ? (
                    <CheckCircle2 className="h-5 w-5 text-green-500" />
                  ) : (
                    <AlertTriangle className="h-5 w-5 text-yellow-500" />
                  )}
                  <span>
                    {getTotalLapsPlanned() > config.RaceLaps
                      ? `${
                          getTotalLapsPlanned() - config.RaceLaps
                        } laps too many`
                      : getTotalLapsPlanned() < config.RaceLaps
                        ? `${
                            config.RaceLaps - getTotalLapsPlanned()
                          } laps remaining`
                        : "Strategy length matches Race length"}
                  </span>
                </div>
              </div>
            </div>

            {/* 2. Visual Timeline Preview */}
            <div className="relative h-32 w-full min-h-0 min-w-0 rounded-lg border border-neutral-800 bg-zinc-100 p-2 dark:bg-neutral-950">
              <span className="absolute top-2 left-2 z-10 text-xs">
                Projected Timeline
              </span>
              <ResponsiveContainer width="100%" height="100%" minWidth={0}>
                <BarChart
                  layout="vertical"
                  data={previewData}
                  margin={{ top: 15, right: 0, left: 0, bottom: 0 }}
                >
                  <XAxis type="number" domain={[0, config.RaceLaps]} hide />
                  <YAxis type="category" dataKey="name" hide />
                  <Tooltip
                    cursor={{ fill: "transparent" }}
                    contentStyle={{
                      backgroundColor: "#171717",
                      border: "1px solid #404040",
                      color: "#fff",
                    }}
                  />
                  {manualStints.map((stint, index) => (
                    <Bar
                      key={`stint_${index}_${stint.tyre}`}
                      dataKey={`stint_${index}_${stint.tyre}`}
                      stackId="a"
                      fill={TYRE_COLORS[stint.tyre]}
                      isAnimationActive={false}
                    />
                  ))}
                  <ReferenceLine x={config.RaceLaps} stroke="#404040" />
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* 3. Selected Stint Editor */}
            {selectedStint ? (
              <div className="flex flex-col gap-4 rounded-xl border border-neutral-700 bg-zinc-100/50 p-4 dark:bg-neutral-800/50">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-bold">Edit Stint Details</h3>
                  <div className="flex gap-2 rounded-lg bg-zinc-300 p-2 dark:rounded-none dark:bg-transparent dark:p-0">
                    {["soft", "medium", "hard", "wet"].map((t) => (
                      <button
                        key={t}
                        onClick={() =>
                          handleUpdateStint(selectedStint.id, "tyre", t)
                        }
                        className={`h-8 w-8 cursor-pointer rounded-full border-2 ${
                          selectedStint.tyre === t
                            ? "scale-110 ring-2 ring-white"
                            : "opacity-40 hover:opacity-100"
                        }`}
                        style={{
                          backgroundColor: "transparent",
                          borderColor: TYRE_COLORS[t],
                          color: TYRE_COLORS[t],
                        }}
                      >
                        {TYRE_LABELS[t]}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-6">
                  <div className="flex flex-col gap-2">
                    <label className="text-sm">Laps in Stint</label>
                    <div className="flex items-center gap-2">
                      <input
                        type="range"
                        min={1}
                        /* max = race laps - other stints' laps */
                        max={
                          config.RaceLaps -
                          manualStints
                            .filter((s) => s.id !== selectedStint.id)
                            .reduce((acc, s) => acc + s.laps, 0)
                        }
                        value={selectedStint.laps}
                        onChange={(e) =>
                          handleUpdateStint(
                            selectedStint.id,
                            "laps",
                            parseInt(e.target.value),
                          )
                        }
                        className="grow accent-neutral-300"
                      />
                      <input
                        type="number"
                        min={1}
                        value={selectedStint.laps}
                        onChange={(e) =>
                          handleUpdateStint(
                            selectedStint.id,
                            "laps",
                            parseInt(e.target.value),
                          )
                        }
                        className="w-16 rounded border border-neutral-700 bg-zinc-100 p-1 text-center dark:bg-neutral-950"
                      />
                    </div>
                  </div>

                  {/* STATS BOX */}
                  <div className="flex flex-col gap-1 rounded-lg border border-neutral-800 bg-zinc-100 p-3 text-xs dark:bg-neutral-900">
                    <span className="mb-1 font-bold">Projections</span>
                    <div className="flex justify-between">
                      <span className="">Wear/Lap:</span>
                      <span className="">
                        {selectedTyreWear > 0
                          ? `${selectedTyreWear.toFixed(2)}%`
                          : "No Data"}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="">Rec. Max Laps:</span>
                      <span className="">{maxSafeLaps}</span>
                    </div>
                    <div className="mt-1 flex justify-between border-t border-neutral-800 pt-1">
                      <span className="">Est. Life Remaining:</span>
                      <span
                        className={`font-bold ${
                          isOverLimit ? "text-red-500" : "text-green-500"
                        }`}
                      >
                        {selectedStint ? (100 - estWear).toFixed(1) : "N/A"}%
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex h-full items-center justify-center italic">
                Select a stint to edit details
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-end gap-2 border-t border-neutral-800 bg-zinc-100 p-4 dark:bg-neutral-900">
          <button
            onClick={onClose}
            className="cursor-pointer rounded-lg px-6 py-2 hover:bg-zinc-200 dark:hover:bg-neutral-800"
          >
            Cancel
          </button>
          <button
            onClick={handleSave}
            className="cursor-pointer rounded-lg bg-zinc-200 px-6 py-2 font-bold text-black shadow-lg shadow-white/10 hover:bg-zinc-300 dark:bg-white dark:hover:bg-neutral-200"
          >
            Save Configuration
          </button>
        </div>
      </div>
    </div>
  );
}
